VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define "web", primary: true do |web|
		web.vm.box = "hashicorp/precise64"
    #web.vm.box_url = "http://files.vagrantup.com/precise64.box"
    web.vm.provision :shell, :path => "boostrap.sh"
    #web.vm.network :private_network, ip: '10.10.10.85'
	end

	config.vm.provider "vmware_fusion" do |v|
		v.gui=false
    v.name="taxonomic-db-server"
    v.vmx["memsize"]="2048"
    v.vmx["numvcpus"]="2"
  end

	config.vm.provider :virtualbox do |vb|
		vb.gui=false
		vb.name="taxonomic-db-server"
		vb.customize ["modifyvm", :id, "--cpus", "2"]
		vb.customize ["modifyvm", :id, "--memory", "2048"]
	end

	config.vm.provider :aws do |aws, override|
      aws.access_key_id = 'XXX'
      aws.secret_access_key = 'XXX'
      aws.keypair_name = 'xxx'
      aws.ami = 'ami-53f14e4e' #'ami-7f805b62'
      aws.region = 'sa-east-1'
      aws.tags = { "Name" => "Taxonomic-DB-Server" }
      override.vm.box = 'taxonomic-db-aws'
      override.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'
      override.ssh.username = 'ubuntu'
      override.ssh.private_key_path = 'xxx.pem'
			#config.ssh.pty = true
  end

end
